wallpaper {
    monitor = HDMI-A-1
    path = ~/dotfiles/wallpapers/HALLEY 𓃚 H.S.U. - 𝅙 - Cover Alt 1.jpg
    fit_mode = fill
  }

wallpaper {
    monitor = DP-3
    path = ~/dotfiles/wallpapers/HALLEY 𓃚 H.S.U. - 𝅙 - Cover Alt 1.jpg
    fit_mode = fill
  }


  splash = false
