# =========================
# GENERAL
# =========================
general {
    disable_loading_bar = true
    hide_cursor = true
}

# =========================
# BACKGROUND
# =========================
background {
    monitor =
    path = ~/Pictures/wallpapers/greenhouse-wallpaper-2.png 
    blur_passes = 1
    blur_size = 8
}

# =========================
# TIME
# =========================
label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 80
    halign = center
    valign = center
}

# =========================
# DATE
# =========================
label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%A, %d %B')"
    font_size = 20
    font_family = JetBrains Mono
    position = 0, 20
    halign = center
    valign = center
}

# =========================
# PASSWORD INPUT
# =========================
input-field {
    monitor =
    size = 250, 50
    position = 0, -80
    halign = center
    valign = center

    dots_center = true
    dots_size = 0.25
    dots_spacing = 0.5

    outer_color = rgb(40,40,40)
    inner_color = rgb(20,20,20)
    font_color = rgb(200,200,200)

    fade_on_empty = true
    placeholder_text = <i>Enter Password</i>
}

