color0 #12131b
color1 #ffb4ab
color2 #bdc2ff
color3 #bdc2ff
color4 #f8acff
color5 #bdc2ff
color6 #bdc2ff
color7 #e3e1ee
color8 #8f8fa1
color9 #ffb4ab
color10 #bdc2ff
color11 #bdc2ff
color12 #f8acff
color13 #bdc2ff
color14 #bdc2ff
color15 #e3e1ee

cursor                #e3e1ee
cursor_text_color     #12131b
background            #12131b
foreground            #e3e1ee
selection_foreground  #c6c5d8
selection_background  #454655
active_border_color   #bdc2ff
inactive_border_color #454655
url_color             #bdc2ff

active_tab_foreground   #000ea4
active_tab_background   #bdc2ff
inactive_tab_foreground #c6c5d8
inactive_tab_background #454655
cursor_trail_color      #c6c5d8
